ALTER TABLE presente_sh.evento
    ADD COLUMN IF NOT EXISTS prog_status VARCHAR(20) DEFAULT 'IDLE', -- IDLE, PROCESSANDO, CONCLUIDO
    ADD COLUMN IF NOT EXISTS prog_atual INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS prog_total INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS prog_label VARCHAR(100)
;
