## Modelo usado no projeto do clube
#FROM openjdk:8-jre
#MAINTAINER Eliseu Rodrigues Menezes <eliseu@eliseu.eng.br>
#EXPOSE 9000
#COPY clube-2.0.0-SNAPSHOT.jar .
#ENV SPRING_DATASOURCE_URL "jdbc:mysql://clubemysqldb/clube?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
#ENTRYPOINT ["java", "-jar", "clube-2.0.0-SNAPSHOT.jar"]

FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copia o jar já construído para o container
COPY presente-0.0.1-SNAPSHOT.jar app.jar

# Variáveis de ambiente para Postgres
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://presentedb:5432/presente_db
ENV SPRING_DATASOURCE_USERNAME=presente
ENV SPRING_DATASOURCE_PASSWORD=presente

# Expõe a porta padrão do Spring Boot
EXPOSE 9000

# Comando para iniciar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]

