### Modelo usado no projeto do clube
#FROM nginx:latest
#COPY dist /usr/share/nginx/html
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY proxy.conf /etc/nginx/proxy.conf
#COPY mime.types /etc/nginx/mime.types



# Frontend Dockerfile - Nginx servindo Angular
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copia os arquivos do build Angular
COPY dist/browser/ /usr/share/nginx/html

# Copia a configuração do Nginx (já incluída no script)
COPY nginx.conf /etc/nginx/nginx.conf
#COPY proxy.conf /etc/nginx/proxy.conf
COPY mime.types /etc/nginx/mime.types

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]